version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: api_o_matic_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: api_o_matic_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: api_o_matic_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./api_o_matic:/app/api_o_matic:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: api_o_matic_local_celeryworker
    container_name: celeryworker
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: api_o_matic_local_celerybeat
    container_name: celerybeat
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: api_o_matic_local_flower
    container_name: flower
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5555:5555"
    command: /start-flower
