@startuml

class Bit {}

enum BitType {}

Bit -left-> BitType

class Source {}

enum SourceType {
    HTML
    JSON
}
Source -right-> SourceType

Bit -right-> Source

class Byte {}

class User {}

User *--> "0..N" Byte
User *--> "0..N" Bit
Byte *--> "0..N" Bit

@enduml
